### ISSUE TITLE
Templates in themes/ are not cached in production

### ISSUE THREAD

**Issue by lowjoel** [chamnap/themes_on_rails#29]
If using a template engine like Slim, templates in themes will be re-compiled on every single request, because the cache of the compiled template is discarded after every request.

I have a PR coming.

**Comment by samsoft00** [comment]
@lowjoel, i've been thinking around this, please how do you cache the template? Thanks

**Comment by lowjoel** [comment]
@samsoft00 I have an implementation in #30.

**Comment by samsoft00** [comment]
@lowjoel currently making use to the gem, how do i know the template is caching, i'm working with `gem 'themes_on_rails', '~> 0.4.0'`? Secondly, whenever i add theme to child Controller, it refused to search the theme directory until i move my implementation to Parent Controller (ApplicationController), below is my implementation, i'm doing the right thing?

```
        def theme_resolver
          subdomains = %w{www admin administrator subdomain user admin demo}
          if request.subdomain.present? && !subdomains.include?(request.subdomain)
            @user = User.find_by(username: request.subdomain)
            return 'basic' if !@user.present? or !['active'].include?@user.site_status #show default
            return @user.site.site_layout.name
          end
          'application'
        end
```

**Comment by chamnap** [comment]
Again `themes_on_rails` is not responsible for caching or compiling templates. What it does is prepend `theme` path a head of `app/views`. Caching templates depends entirely on those specific template like `haml-rails` or `liquid-rails`.
